- hosts: all

  vars_files:
    - api-keys.yml
  tasks:

    - name: Install docker
      yum: name=docker-io

    - name: Install pip
      yum: name=python-pip

    - name: Install docker python lib from pip
      pip: name=docker-py==1.1.0

    - name: Deploy sounds.so backend
      docker:
        name: sounds-so-backend
        image: soundsso/sounds-so-backend

        state: reloaded
        pull: always

        restart_policy: always

        ports:
          - '{{ sso_backend_port }}:8080'

        env:
          FREESOUND_API_TOKEN: "{{ sso_backend_freesound_api_token }}"
          SLACK_TEAM_TOKEN: "{{ sso_backend_slack_team_token }}"
          SLACK_INCOMING_WEBHOOK_URL: "{{ sso_backend_slack_incoming_webhook_url }}"
          SOUNDS_SO_BASE_URI: "http://sounds.so/"